language: rust
cache: cargo
rust:
  - stable
  - nightly

env:
  - FEATURE=default
  - FEATURE=awskms
  - FEATURE=gcpkms

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cargo build --verbose --features $FEATURE
  - cargo test --verbose --features $FEATURE
